# Generated by Django 4.2.7 on 2024-04-01 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalmanager',
            name='name',
        ),
        migrations.AddField(
            model_name='generalmanager',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
