# Generated by Django 4.2.7 on 2024-04-02 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
        ('patient', '0003_remove_patient_applied_treatment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='applied_treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_treatment', to='treatment.treatment'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='recommended_treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_treatment', to='treatment.treatment'),
        ),
    ]
