# Generated by Django 4.2.7 on 2024-04-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('treatment', '0001_initial'),
        ('assistant', '0001_initial'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='assigned_treatment',
        ),
        migrations.AddField(
            model_name='patient',
            name='applied_treatment',
            field=models.ManyToManyField(blank=True, related_name='applied_treatment', to='treatment.treatment'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='assistants',
            field=models.ManyToManyField(blank=True, to='assistant.assistant'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(blank=True, to='doctor.doctor'),
        ),
        migrations.RemoveField(
            model_name='patient',
            name='recommended_treatment',
        ),
        migrations.AddField(
            model_name='patient',
            name='recommended_treatment',
            field=models.ManyToManyField(blank=True, related_name='recommended_treatment', to='treatment.treatment'),
        ),
    ]
